version: 1.5.{build}
image: 
- Visual Studio 2017
configuration:
- Release
pull_requests:
  do_not_increment_build_number: true
skip_branch_with_pr: true
before_build:
- cmd: nuget restore
build:
  parallel: true
  verbosity: minimal
before_test:
- cmd: Dotnet test "Project2015To2017Tests\Project2015To2017Tests.csproj"
after_build:
- cmd: dotnet publish -f net46 -c Release -o ./out/net46 ./Project2015To2017/Project2015To2017.csproj
- cmd: dotnet publish -f netcoreapp1.1 -c Release -o ./out/netcoreapp1.1 ./Project2015To2017/Project2015To2017.csproj
- cmd: 7z a ./Project2015To2017/out/CSProj2015To2017.zip ./Project2015To2017/out/*.*

artifacts:
  - path: ./Project2015To2017/out/CSProj2015To2017.zip
    name: out-zip
    
deploy:
  release: CSProj2015To2017-v$(APPVEYOR_REPO_TAG_NAME)
  description: 'Automatically built release v$(APPVEYOR_REPO_TAG_NAME).'
  provider: GitHub  
  auth_token:
    secure: "LYFGDMnT4oJLpCsZUkhL/oTnG3ZpQnsjaTc10DfTf/jbkXtzctRkXEu2ea3YnyqP" # your encrypted token from GitHub
  artifact: out-zip                # upload all NuGet packages to release assets
  draft: false
  prerelease: true
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only