version: 1.4.{build}
image: 
- Visual Studio 2017
configuration:
- Debug
- Release
pull_requests:
  do_not_increment_build_number: true
skip_branch_with_pr: true
before_build:
- appveyor-retry dotnet restore -v Minimal
build_script:
- dotnet build -c %CONFIGURATION%
test_script:
- dotnet test -c %CONFIGURATION%
