version: 4.0.{build}
skip_tags: true
image: 
- Visual Studio 2017
configuration:
- Release
pull_requests:
  do_not_increment_build_number: true
skip_branch_with_pr: true
environment:
  LOGGER: '/l:"C:\Program Files\AppVeyor\BuildAgent\dotnetcore\Appveyor.MSBuildLogger.dll"'
  LIBRARY: './Project2015To2017/Project2015To2017.csproj'
  LEGACYCLITOOL: './Project2015To2017.Console/Project2015To2017.Console.csproj'
  CLITOOL: './Project2015To2017.Migrate2017.Tool/Project2015To2017.Migrate2017.Tool.csproj'
build_script:
  - cmd: dotnet build %LOGGER% -v m -c %configuration%
  - cmd: dotnet pack %LIBRARY% %LOGGER% -v m -c %configuration% --no-build
  - cmd: dotnet pack %LEGACYCLITOOL% %LOGGER% -v m -c %configuration% --no-build /p:Pack=true
  - cmd: dotnet pack %CLITOOL% %LOGGER% -v m -c %configuration% --no-build /p:Pack=true
  - cmd: dotnet publish %CLITOOL% %LOGGER% -v m -c %configuration% -f netcoreapp2.1 -o ./out/netcoreapp2.1 --no-build
  - cmd: dotnet publish %CLITOOL% %LOGGER% -v m -c %configuration% -f net461 -o ./out/net461 --no-build
after_build:
  - cmd: 7z a ./Project2015To2017/out/dotnet-migrate-2017.zip ./Project2015To2017.Migrate2017.Tool/out/*
test_script:
  - cmd: dotnet test Project2015To2017.Tests/Project2015To2017.Tests.csproj -c %configuration% --no-build --test-adapter-path:. --logger:Appveyor

artifacts:
  - path: ./Project2015To2017.Console/bin/$(configuration)/Project2015To2017.Cli.**.nupkg
    name: global-tool-legacy
  - path: ./Project2015To2017.Migrate2017.Tool/bin/$(configuration)/Project2015To2017.Migrate2017.Tool.**.nupkg
    name: global-tool
  - path: ./Project2015To2017/out/dotnet-migrate-2017.zip
    name: out-zip
  - path: Project2015To2017\bin\$(configuration)\Project2015To2017.**.nupkg
    name: nupkg
    
deploy:
- provider: NuGet
  api_key:
    secure: i6ZaMLxF/Jbkh7SgDJuFIwpcrXl1BcNI5vd5Re33EEQV7PrZ71F6MpuIDF7glY/o
  skip_symbols: false
  artifact: nupkg
  
- provider: NuGet
  api_key:
    secure: +o0/XtevmiegEOJLY9u6bm57gbFvGT/0mraL78vBCtEjNkdjWkZEQGxiL//UP88S
  skip_symbols: false
  artifact: global-tool-legacy
  
- provider: NuGet
  api_key:
    secure: 5MwxrP9zjSXiJ2WUmdQSR98h+ys28LHiDzVBaFmrDCDvBhvNf+QqDaNDs/+LhVQU
  skip_symbols: false
  artifact: global-tool

- provider: GitHub
  release: dotnet-migrate-2017-v$(APPVEYOR_BUILD_VERSION)
  description: 'Automatically built release v$(APPVEYOR_BUILD_VERSION).'
  auth_token:
    secure: "LYFGDMnT4oJLpCsZUkhL/oTnG3ZpQnsjaTc10DfTf/jbkXtzctRkXEu2ea3YnyqP"
  artifact: out-zip
  draft: true
  prerelease: true
  on:
    branch: master        # deploy on tag push only
    
# build cache to preserve files/folders between builds
cache:
  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
  - '%LocalAppData%\NuGet\Cache'